id: P3C33AC53
initial_creation_type: ocr
source_metadata:
  volumes:
    a95a4d700d174d68b11629f4495c0471:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ལུགས་ཀྱི་བསྟན་བཅོས་སྐྱེ་བོ་གསོ་བའི་ཐིགས་པ།
      total_pages: 1872
      volume_number: 114
